import org.objectweb.asm.*;
import static org.objectweb.asm.Opcodes.*;
import js.builtins.array;
import js.runtime.*;

/**
 * Real end-to-end test: Uses actual Torque-generated Java code.
 *
 * Pipeline being tested:
 * 1. Torque source (.tq) -> Rust parser/codegen -> Java source
 * 2. Java source -> javac -> .class files (this compilation)
 * 3. At runtime: Call build_* methods -> ASM generates bytecode -> JVM runs it
 */
public class RealE2ETest {
    public static void main(String[] args) throws Exception {
        System.out.println("=== Real End-to-End Test ===");
        System.out.println("Testing actual Torque codegen output\n");

        // Create a ClassWriter to receive the generated bytecode
        ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_FRAMES | ClassWriter.COMPUTE_MAXS);
        cw.visit(V11, ACC_PUBLIC, "GeneratedArrayOps", null, "java/lang/Object", null);

        // Add default constructor
        MethodVisitor init = cw.visitMethod(ACC_PUBLIC, "<init>", "()V", null, null);
        init.visitCode();
        init.visitVarInsn(ALOAD, 0);
        init.visitMethodInsn(INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false);
        init.visitInsn(RETURN);
        init.visitMaxs(1, 1);
        init.visitEnd();

        // Call the REAL Torque-generated build method for SmiAdd
        // (ArrayPush and GetElement have other issues with field access types - TODO)
        System.out.println("Calling Torque-generated build_SmiAdd...");
        array.build_SmiAdd(cw);

        cw.visitEnd();

        // Get the bytecode
        byte[] bytecode = cw.toByteArray();
        System.out.println("\nGenerated " + bytecode.length + " bytes of bytecode");

        // Verify bytecode is valid by loading the class
        ClassLoader loader = new ClassLoader() {
            @Override
            protected Class<?> findClass(String name) {
                return defineClass(name, bytecode, 0, bytecode.length);
            }
        };

        try {
            Class<?> generatedClass = loader.loadClass("GeneratedArrayOps");
            System.out.println("Successfully loaded generated class: " + generatedClass.getName());

            // List all generated methods
            System.out.println("\nGenerated methods:");
            for (java.lang.reflect.Method m : generatedClass.getDeclaredMethods()) {
                System.out.println("  - " + m.getName() + " " +
                    java.util.Arrays.toString(m.getParameterTypes()));
            }

            // Actually invoke the generated SmiAdd method!
            System.out.println("\nTesting SmiAdd(3, 4)...");
            java.lang.reflect.Method smiAdd = generatedClass.getMethod("SmiAdd", Smi.class, Smi.class);
            Smi result = (Smi) smiAdd.invoke(null, new Smi(3), new Smi(4));
            System.out.println("Result: " + result + " (value=" + result.intValue() + ")");

            if (result.intValue() == 7) {
                System.out.println("\n=== End-to-end test PASSED ===");
                System.out.println("The Torque codegen produced valid Java that generates valid JVM bytecode!");
                System.out.println("AND the generated bytecode computes correct results!");
            } else {
                System.err.println("ERROR: Expected 7, got " + result.intValue());
                System.exit(1);
            }

        } catch (VerifyError e) {
            System.err.println("\n=== BYTECODE VERIFICATION FAILED ===");
            System.err.println("The generated bytecode is invalid:");
            System.err.println(e.getMessage());
            System.exit(1);
        }
    }
}
