package e2e;

import org.objectweb.asm.*;
import static org.objectweb.asm.Opcodes.*;

/**
 * This file simulates what the Rust Torque codegen produces.
 * It demonstrates the code pattern: Java source that uses ASM to emit bytecode.
 *
 * Original Torque:
 *   namespace math {
 *       macro Add(a: int32, b: int32): int32 { return a + b; }
 *       macro Sub(a: int32, b: int32): int32 { return a - b; }
 *       macro Mul(a: int32, b: int32): int32 { return a * b; }
 *       macro Max(a: int32, b: int32): int32 { if (a > b) { return a; } return b; }
 *       macro Abs(x: int32): int32 { if (x < 0) { return 0 - x; } return x; }
 *   }
 */
public class TorqueGenerated {

    // Generated from: macro Add(a: int32, b: int32): int32 { return a + b; }
    public static void build_Add(ClassWriter cw) {
        MethodVisitor mv = cw.visitMethod(ACC_PUBLIC | ACC_STATIC, "Add", "(II)I", null, null);
        mv.visitCode();
        mv.visitVarInsn(ILOAD, 0);  // a
        mv.visitVarInsn(ILOAD, 1);  // b
        mv.visitInsn(IADD);
        mv.visitInsn(IRETURN);
        mv.visitMaxs(-1, -1);
        mv.visitEnd();
    }

    // Generated from: macro Sub(a: int32, b: int32): int32 { return a - b; }
    public static void build_Sub(ClassWriter cw) {
        MethodVisitor mv = cw.visitMethod(ACC_PUBLIC | ACC_STATIC, "Sub", "(II)I", null, null);
        mv.visitCode();
        mv.visitVarInsn(ILOAD, 0);  // a
        mv.visitVarInsn(ILOAD, 1);  // b
        mv.visitInsn(ISUB);
        mv.visitInsn(IRETURN);
        mv.visitMaxs(-1, -1);
        mv.visitEnd();
    }

    // Generated from: macro Mul(a: int32, b: int32): int32 { return a * b; }
    public static void build_Mul(ClassWriter cw) {
        MethodVisitor mv = cw.visitMethod(ACC_PUBLIC | ACC_STATIC, "Mul", "(II)I", null, null);
        mv.visitCode();
        mv.visitVarInsn(ILOAD, 0);  // a
        mv.visitVarInsn(ILOAD, 1);  // b
        mv.visitInsn(IMUL);
        mv.visitInsn(IRETURN);
        mv.visitMaxs(-1, -1);
        mv.visitEnd();
    }

    // Generated from: macro Max(a: int32, b: int32): int32 { if (a > b) { return a; } return b; }
    public static void build_Max(ClassWriter cw) {
        MethodVisitor mv = cw.visitMethod(ACC_PUBLIC | ACC_STATIC, "Max", "(II)I", null, null);
        mv.visitCode();
        Label else_label = new Label();
        Label endif_label = new Label();

        mv.visitVarInsn(ILOAD, 0);  // a
        mv.visitVarInsn(ILOAD, 1);  // b
        mv.visitJumpInsn(IF_ICMPLE, else_label);  // if a <= b goto else

        // then branch: return a
        mv.visitVarInsn(ILOAD, 0);
        mv.visitInsn(IRETURN);

        mv.visitLabel(else_label);
        // else branch: return b
        mv.visitVarInsn(ILOAD, 1);
        mv.visitInsn(IRETURN);

        mv.visitMaxs(-1, -1);
        mv.visitEnd();
    }

    // Generated from: macro Abs(x: int32): int32 { if (x < 0) { return 0 - x; } return x; }
    public static void build_Abs(ClassWriter cw) {
        MethodVisitor mv = cw.visitMethod(ACC_PUBLIC | ACC_STATIC, "Abs", "(I)I", null, null);
        mv.visitCode();
        Label else_label = new Label();

        mv.visitVarInsn(ILOAD, 0);  // x
        mv.visitJumpInsn(IFGE, else_label);  // if x >= 0 goto else

        // then branch: return 0 - x
        mv.visitInsn(ICONST_0);
        mv.visitVarInsn(ILOAD, 0);
        mv.visitInsn(ISUB);
        mv.visitInsn(IRETURN);

        mv.visitLabel(else_label);
        // else branch: return x
        mv.visitVarInsn(ILOAD, 0);
        mv.visitInsn(IRETURN);

        mv.visitMaxs(-1, -1);
        mv.visitEnd();
    }

    public static void main(String[] args) throws Exception {
        System.out.println("=== Torque-Generated Bytecode Test ===\n");

        // Create the class
        ClassWriter cw = new ClassWriter(ClassWriter.COMPUTE_FRAMES | ClassWriter.COMPUTE_MAXS);
        cw.visit(V11, ACC_PUBLIC, "e2e/MathBuiltins", null, "java/lang/Object", null);

        // Add constructor
        MethodVisitor constructor = cw.visitMethod(ACC_PUBLIC, "<init>", "()V", null, null);
        constructor.visitCode();
        constructor.visitVarInsn(ALOAD, 0);
        constructor.visitMethodInsn(INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false);
        constructor.visitInsn(RETURN);
        constructor.visitMaxs(1, 1);
        constructor.visitEnd();

        // Build all methods from Torque codegen
        build_Add(cw);
        build_Sub(cw);
        build_Mul(cw);
        build_Max(cw);
        build_Abs(cw);

        cw.visitEnd();
        byte[] bytecode = cw.toByteArray();

        // Load dynamically
        ClassLoader loader = new ClassLoader() {
            @Override
            protected Class<?> findClass(String name) {
                return defineClass(name, bytecode, 0, bytecode.length);
            }
        };
        Class<?> mathClass = loader.loadClass("e2e.MathBuiltins");

        // Get methods via reflection
        java.lang.reflect.Method add = mathClass.getMethod("Add", int.class, int.class);
        java.lang.reflect.Method sub = mathClass.getMethod("Sub", int.class, int.class);
        java.lang.reflect.Method mul = mathClass.getMethod("Mul", int.class, int.class);
        java.lang.reflect.Method max = mathClass.getMethod("Max", int.class, int.class);
        java.lang.reflect.Method abs = mathClass.getMethod("Abs", int.class);

        // Test Add
        System.out.println("Testing Add:");
        assertEq((Integer) add.invoke(null, 3, 4), 7, "Add(3, 4)");
        assertEq((Integer) add.invoke(null, -5, 10), 5, "Add(-5, 10)");
        assertEq((Integer) add.invoke(null, 0, 0), 0, "Add(0, 0)");

        // Test Sub
        System.out.println("\nTesting Sub:");
        assertEq((Integer) sub.invoke(null, 10, 4), 6, "Sub(10, 4)");
        assertEq((Integer) sub.invoke(null, 5, 10), -5, "Sub(5, 10)");

        // Test Mul
        System.out.println("\nTesting Mul:");
        assertEq((Integer) mul.invoke(null, 6, 7), 42, "Mul(6, 7)");
        assertEq((Integer) mul.invoke(null, -3, 4), -12, "Mul(-3, 4)");
        assertEq((Integer) mul.invoke(null, 0, 100), 0, "Mul(0, 100)");

        // Test Max
        System.out.println("\nTesting Max:");
        assertEq((Integer) max.invoke(null, 10, 5), 10, "Max(10, 5)");
        assertEq((Integer) max.invoke(null, 5, 10), 10, "Max(5, 10)");
        assertEq((Integer) max.invoke(null, 7, 7), 7, "Max(7, 7)");
        assertEq((Integer) max.invoke(null, -3, -5), -3, "Max(-3, -5)");

        // Test Abs
        System.out.println("\nTesting Abs:");
        assertEq((Integer) abs.invoke(null, 5), 5, "Abs(5)");
        assertEq((Integer) abs.invoke(null, -5), 5, "Abs(-5)");
        assertEq((Integer) abs.invoke(null, 0), 0, "Abs(0)");

        System.out.println("\n=== All " + testCount + " tests passed! ===");
    }

    static int testCount = 0;

    static void assertEq(int actual, int expected, String desc) {
        testCount++;
        if (actual == expected) {
            System.out.println("  ✓ " + desc + " = " + actual);
        } else {
            System.err.println("  ✗ " + desc + ": expected " + expected + ", got " + actual);
            System.exit(1);
        }
    }
}
